---
title: "covenant of majors"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Bnchmarking de la imlementación de políticas sustentables

En este trabajo analizaremos que tan mal es el desempeño de los intendentes del municipio (las acciones de los municipios de GC, Las Heras, Ciudad, Maipú,...)


```{r}
co2 <- rnorm(50,200,30)
hist(co2)

```

Column {data-width=350}
-----------------------------------------------------------------------

### Participación de cada municipio


```{r}
muni <-c("Capital","Godoy Cruz", "Guaymallén","Maipú", "Luján", "Las Heras")
munico2 <- c(300,150,270,320,412,330)
pie(munico2, labels = (muni))
```

### Transporte público

```{r}

```

RSU(residuos solidos urbanos)
===========
```{r}

```
Reciclado 
===========
```{r}

```
RAEE(residuos de aparatos eléctrico y electrónicos) 
==========

```{r}

```

Benchamrking de intendentes
=====



